package bourse;


/**
* bourse/BoursePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bourse.idl
* Tuesday, January 16, 2018 3:40:37 PM PST
*/

public abstract class BoursePOA extends org.omg.PortableServer.Servant
 implements bourse.BourseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCotations", new java.lang.Integer (0));
    _methods.put ("getMoyennesCotations", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // bourse/Bourse/getCotations
       {
         String cs = in.read_string ();
         bourse.CCotation $result[] = null;
         $result = this.getCotations (cs);
         out = $rh.createReply();
         bourse.cotsHelper.write (out, $result);
         break;
       }

       case 1:  // bourse/Bourse/getMoyennesCotations
       {
         String cs = in.read_string ();
         double $result = (double)0;
         $result = this.getMoyennesCotations (cs);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:bourse/Bourse:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Bourse _this() 
  {
    return BourseHelper.narrow(
    super._this_object());
  }

  public Bourse _this(org.omg.CORBA.ORB orb) 
  {
    return BourseHelper.narrow(
    super._this_object(orb));
  }


} // class BoursePOA
