package bourse;

/**
* bourse/CCotationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bourse.idl
* Tuesday, January 16, 2018 3:40:37 PM PST
*/

public final class CCotationHolder implements org.omg.CORBA.portable.Streamable
{
  public bourse.CCotation value = null;

  public CCotationHolder ()
  {
  }

  public CCotationHolder (bourse.CCotation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bourse.CCotationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bourse.CCotationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bourse.CCotationHelper.type ();
  }

}
