package bourse;


/**
* bourse/cotsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bourse.idl
* Tuesday, January 16, 2018 3:40:37 PM PST
*/

abstract public class cotsHelper
{
  private static String  _id = "IDL:bourse/cots:1.0";

  public static void insert (org.omg.CORBA.Any a, bourse.CCotation[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static bourse.CCotation[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = bourse.CCotationHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (bourse.cotsHelper.id (), "cots", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static bourse.CCotation[] read (org.omg.CORBA.portable.InputStream istream)
  {
    bourse.CCotation value[] = null;
    int _len0 = istream.read_long ();
    value = new bourse.CCotation[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = bourse.CCotationHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, bourse.CCotation[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      bourse.CCotationHelper.write (ostream, value[_i0]);
  }

}
