
package ws.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BourseWS", targetNamespace = "http://ws/test", wsdlLocation = "file:/C:/Documents%20and%20Settings/xP/workspace/JAXWS_BourseClient/src/Bourse.wsdl")
public class BourseWS
    extends Service
{

    private final static URL BOURSEWS_WSDL_LOCATION;
    private final static WebServiceException BOURSEWS_EXCEPTION;
    private final static QName BOURSEWS_QNAME = new QName("http://ws/test", "BourseWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Documents%20and%20Settings/xP/workspace/JAXWS_BourseClient/src/Bourse.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOURSEWS_WSDL_LOCATION = url;
        BOURSEWS_EXCEPTION = e;
    }

    public BourseWS() {
        super(__getWsdlLocation(), BOURSEWS_QNAME);
    }

    public BourseWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOURSEWS_QNAME, features);
    }

    public BourseWS(URL wsdlLocation) {
        super(wsdlLocation, BOURSEWS_QNAME);
    }

    public BourseWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOURSEWS_QNAME, features);
    }

    public BourseWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BourseWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BourseService
     */
    @WebEndpoint(name = "BourseServicePort")
    public BourseService getBourseServicePort() {
        return super.getPort(new QName("http://ws/test", "BourseServicePort"), BourseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BourseService
     */
    @WebEndpoint(name = "BourseServicePort")
    public BourseService getBourseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/test", "BourseServicePort"), BourseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOURSEWS_EXCEPTION!= null) {
            throw BOURSEWS_EXCEPTION;
        }
        return BOURSEWS_WSDL_LOCATION;
    }

}
