package bourse;


/**
* bourse/cotsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bourse.idl
* Tuesday, January 16, 2018 3:39:57 PM PST
*/

public final class cotsHolder implements org.omg.CORBA.portable.Streamable
{
  public bourse.CCotation value[] = null;

  public cotsHolder ()
  {
  }

  public cotsHolder (bourse.CCotation[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bourse.cotsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bourse.cotsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bourse.cotsHelper.type ();
  }

}
